name: smoke
base_config: base.yaml
output_csv: ./benchmark/results/smoke_multiseed_results.csv

datasets:
  - compas

models:
  - linear
  - mlp
  - randomforest

methods:
  - apas
  - arg_ensembling
  - cchvae
  - cemsp
  - cfrl
  - cfvae
  - claproar
  - clue
  - cogs
  - cols
  - cruds
  - cvas_proj
  - dice
  - diverse_dist
  - face
  - feature_tweak
  - gravitational
  - gs
  - larr
  - mace
  - probe
  - proplace
  - rbr
  - revise
  - roar
  - sns
  - trex
  - wachter

benchmark:
  sample_seeds: [0, 1, 2, 3]
  # sample_target: 5
  # min_factuals: 2
