from method.apas.apas import ApasMethod
from method.arg_ensembling.arg_ensembling import ArgEnsemblingMethod
from method.cchvae.cchvae import CchvaeMethod
from method.cfrl.cfrl import CfrlMethod
from method.cfvae.cfvae import CfvaeMethod
from method.claproar.claproar import ClaproarMethod
from method.clue.clue import ClueMethod
from method.cogs.cogs import CogsMethod
from method.cols.cols import ColsMethod
from method.cruds.cruds import CrudsMethod
from method.cvas_proj.cvas_proj import CvasProjMethod
from method.dice.dice import DiceMethod
from method.diverse_dist.diverse_dist import DiverseDistMethod
from method.face.face import FaceMethod
from method.feature_tweak.feature_tweak import FeatureTweakMethod
from method.gravitational.gravitational import GravitationalMethod
from method.gs.gs import GsMethod
from method.larr.larr import LarrMethod
from method.mace.mace import MaceMethod
from method.method_object import MethodObject
from method.probe.probe import ProbeMethod
from method.proplace.proplace import ProplaceMethod
from method.rbr.rbr import RbrMethod
from method.revise.revise import ReviseMethod
from method.roar.roar import RoarMethod
from method.sns.sns import SnsMethod
from method.toy.toy import ToyMethod
from method.trex.trex import TrexMethod
